### ISSUE TITLE
Relative instead of absolute paths

### ISSUE THREAD

**Issue by jakobrosenberg** [Gerrit0/typedoc-plugin-missing-exports#12] opened 2022-03-31 08:21 UTC
Is it possible to change this to a relative path? I imagine it could cause confusion or even breakage on other machines.

![image](https://user-images.githubusercontent.com/4153004/161010395-bfca139b-6a74-4e32-ac9e-ed50f1c4816e.png)

**Comment by Gerrit0** [comment] 2022-03-31 13:31
Definitely needs investigation; this looks like a bug to me.

**Comment by jimblanc** [comment] 2024-02-16 17:57
Running into the same issue and noticed this was closed as "not planned". @jakobrosenberg were you ever able to resolve? @Gerrit0 any idea of the root-cause?

**Comment by Gerrit0** [comment] 2024-02-16 23:13
GitHub shows not planned for any of the non-"done" reasons. In this case, closed because no minimal reproduction was provided so it is unworkable.

**Comment by jimblanc** [comment] 2024-02-16 23:29
That's fair, I'll work on seeing if I can boil down a reproduction app.

**Comment by blutorange** [comment] 2024-09-23 06:52
@Gerrit0 I made a sample project for testing how to document the JavaScript code of a different project. I'll probably change a lot of the setup, but also came across this issue. I made a branch with the state where this issue occurs, try the following to reproduce it: 

```sh
git clone https://github.com/blutorange/primefaces-js-refactor-test.git
cd primefaces-js-refactor-test/
git checkout typedoc-plugin-missing-exports-issue-12
npm install
cd packages/core/
npx tsc
npm run typedoc
open docs/index.html
```

Then open `docs/index.html`, I get the following with absolute links:

![image](https://github.com/user-attachments/assets/1c6d4b1f-1eb3-47df-bdb2-d845818d8cfb)

**Comment by Gerrit0** [comment] 2024-09-24 03:33
Ah, that makes a ton of sense... ick. It's probably going to require some terrible hack to fix this.

**Comment by blutorange** [comment] 2024-11-13 11:47
@Gerrit0 For reference, this can also cause an error when generating the documentation, in conjunction with yarn's [PNP mode](https://yarnpkg.com/features/pnp):

> [error] Could not write /home/user/tmp/repro/primefaces-js-refactor-test/docs/modules/_internal_.__home_user_tmp_repro_primefaces_js_refactor_test__yarn___virtual____fullcalendar_interaction_virtual_507a71b689_4__yarn_berry_cache__fullcalendar_interaction_npm_6_1_15_20b6da9676_10c0_zip_node_modules__fullcalendar_interaction_index_.html

The OS complains because the filename it tries to use it too long (`touch: cannot touch '...': File name too long`). Simple reproduction:

```sh
git clone https://github.com/blutorange/primefaces-js-refactor-test.git
cd primefaces-js-refactor-test/
git checkout demo-typedoc-issue-long-file-names
yarn install
yarn typedoc src/index.ts --out docs --plugin typedoc-plugin-missing-exports
```

This happens as soon as there are multiple imports / external modules. When you comment out one of the imports in [index.ts](https://github.com/blutorange/primefaces-js-refactor-test/blob/demo-typedoc-issue-long-file-names/src/index.ts), it only generates names like `docs/classes/_internal_.Component.html`

Though perhaps this would need to be addressed by the typedoc core, that it finds a way to avoid long file names?

**Closed as completed** 2024-11-15 22:44 UTC
Labels: bug
